### ISSUE TITLE
Update to 2.22.1

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/git222#1]
This RPM spec file needs to be [updated to 2.22.1](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.22.1.txt).  If you aren't familiar with RPM spec files, check out [this guide](https://rpm-packaging-guide.github.io).

**Comment by blackfile** [comment]
@carlwgeorge  Updated completed #2

**Comment by carlwgeorge** [comment]
Thanks for that @blackfile, I've published git222-2.22.1-1 to the testing repo.
