### ISSUE TITLE
backport upstream bugfixes from 2.24

### ISSUE THREAD

**Issue by mricon** [iusrepo/git222#3]
There are two benign but annoying bugs in git-2.22.x that affect the server-side:

1. A bug in line-wrapping causes remote operations to output copious screen junk: https://public-inbox.org/git/c6b51eaf-79b1-6fb9-6085-2d1a45b739a6@suse.cz/ . This results in confusion and lots of email to server admins.
2. A bug in commit-graph.c causes "git fsck" runs to output progress information to the console even when running without a terminal present (https://github.blog/2019-11-03-highlights-from-git-2-24/#commit-graphs-by-default). This results in cron mailbombs from automated fsck processes running on the server for repos with commit-graph files.

Both of these are fixed in git-2.24.0, so it probably makes sense to get that package out sooner than later. I ended up building it locally just to address the above two problems, using git222.spec as the base and updating name/version to match.

**Comment by carlwgeorge** [comment]
Creating a git224 package is certainly something we can consider.  That would be a new package request, which we handle on our [wishlist](https://github.com/iusrepo/wishlist).  Create a separate issue over there and I'll take a look once I'm able.

Regarding fixing the issue in git222, we have two options.

1. Encourage upstream to backport the fixes to the 2.22.x series, and release a 2.22.2 version.  They may decline if it's not security related.

2. Isolate the specific commits necessary to fix the issue and backport them ourselves as a patch in the git222 package.  I wasn't able to determine this from the links you provided, so I'd appreciate any help here that you can provide.

**Comment by carlwgeorge** [comment]
Closing as we have git224 now.  If upstream does a new 2.22.x release with the fixes we will of course update git222 to that version.
