### ISSUE TITLE
Not installable on UBI 7 due to missing packages

### ISSUE THREAD

**Issue by jglick** [iusrepo/git222#4]
Trying to follow the [instructions](https://ius.io/setup)

```dockerfile
FROM registry.access.redhat.com/ubi7:7.7-178
RUN yum --disableplugin=subscription-manager install -y \
    https://repo.ius.io/ius-release-el7.rpm \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum --disableplugin=subscription-manager install -y git222
```

fails:

```
…
--> Finished Dependency Resolution
Error: Package: git222-core-2.22.1-1.el7.ius.x86_64 (ius)
           Requires: libpcre2-8.so.0()(64bit)
Error: Package: git222-2.22.1-1.el7.ius.x86_64 (ius)
           Requires: libsecret-1.so.0()(64bit)
Error: Package: git222-2.22.1-1.el7.ius.x86_64 (ius)
           Requires: emacs-filesystem >= 24.3
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

`git2u` also fails:

```
Error: Package: git2u-2.16.5-1.ius.el7.x86_64 (ius)
           Requires: libsecret-1.so.0()(64bit)
```

**Comment by carlwgeorge** [comment]
UBI does not contain all the same packages as RHEL or CentOS.  As you can see in your error, there are dependencies that cannot be met.  RHEL and CentOS have the necessary packages (pcre2, libsecret, and emacs-filesystem).  The [UBI FAQ](https://developers.redhat.com/articles/ubi-faq/) (question 32) describes how to request a package be included in the UBI repos.  If you have a RHEL subscription you can just use a proper RHEL image, or use CentOS instead.

There is nothing here that IUS can fix.

**Comment by jglick** [comment]
Thanks for clarification. Perhaps the ius.io FAQ should then explicitly state that it does not support UBI?

**Comment by carlwgeorge** [comment]
Yes, that's a great suggestion.  I saw your pull request, I'll review and merge it soon.  Thanks!
