### ISSUE TITLE
Issue installing git222 on Centos 7

### ISSUE THREAD

**Issue by mathomp4** [iusrepo/git222#5]
This might be a FAQ, but I'm having some issues with IUS, but only in the last few days. I'm trying to update a Dockerfile where I do:
```
RUN yum install -y https://centos7.iuscommunity.org/ius-release.rpm && \
    yum install -y git2u-all byacc bison flex expat-devel texinfo epel-release && \
    yum install -y file automake autoconf libtool && \
    yum install -y cmake3 && ln -s /usr/bin/cmake3 /usr/bin/cmake && ln -s /usr/bin/ccmake3 /usr/bin/ccmake && \
```
because I need git 2.x, et al, as part of the setup. And I'm pretty sure it worked last week as I've been building/rebuilding Docker images because...well...I don't know what I'm doing really. (Docker newbie :) )

But, today when I try it:
```
yum install -y git2u-all
...
--> Processing Conflict: git216-2.16.6-2.el7.ius.x86_64 conflicts git < 2.16.6-2.el7.ius
--> Processing Conflict: git216-core-2.16.6-2.el7.ius.x86_64 conflicts git-core < 2.16.6-2.el7.ius
--> Processing Conflict: git216-perl-Git-2.16.6-2.el7.ius.noarch conflicts perl-Git < 2.16.6-2.el7.ius
--> Finished Dependency Resolution
Error: git216-perl-Git conflicts with perl-Git-1.8.3.1-21.el7_7.noarch
Error: git216 conflicts with git-1.8.3.1-21.el7_7.x86_64
Error: git216-core conflicts with git-1.8.3.1-21.el7_7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
I did a bit of `yum search` and saw `git222-all` but:
```
yum install -y git222-all
...
--> Processing Conflict: git222-core-2.22.2-1.el7.ius.x86_64 conflicts git-core < 2.22.2-1.el7.ius
--> Processing Conflict: git222-perl-Git-2.22.2-1.el7.ius.noarch conflicts perl-Git < 2.22.2-1.el7.ius
--> Processing Conflict: git222-2.22.2-1.el7.ius.x86_64 conflicts git < 2.22.2-1.el7.ius
--> Finished Dependency Resolution
Error: git222-perl-Git conflicts with perl-Git-1.8.3.1-21.el7_7.noarch
Error: git222-core conflicts with git-1.8.3.1-21.el7_7.x86_64
Error: git222 conflicts with git-1.8.3.1-21.el7_7.x86_64
```
Now, I'm moving on by adding `yum erase -y git` in my setup, but I didn't know if there was a better way to do this?

**Comment by carlwgeorge** [comment]
git2u was renamed to git216, but I don't think that's the problem here.  Even before the rename, git2u conflicted with stock git, just like git216, git222, and git224 do.  My guess is your base image changed and started including stock git.  The simplest way to address it is what you did, erasing stock git before attempting to install any of the IUS git* packages.  You could also do it with yum shell in a single transaction, but that syntax is a little trickier, and I don't remember off the top of my head how to make it cooperate in a Dockerfile.
